# Generated by Django 5.1.7 on 2025-04-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.TextField(max_length=500)),
                ('password', models.IntegerField()),
                ('is_staff', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
            ],
        ),
    ]
